// <auto-generated />
using KanbanBlazorServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KanbanBlazorServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240215164530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("KanbanBlazorServer.Models.TaskData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Data");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Make dinner",
                            Status = "To Do"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Clean kitchen",
                            Status = "To Do"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clean dishes and load dishwasher",
                            Status = "To Do"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Exercise",
                            Status = "In Process"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Make a journal entry",
                            Status = "In Process"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Check morning email",
                            Status = "In Process"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Make morning coffee",
                            Status = "Done"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
